package brix.web.nodepage.markup;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Iterator;
import java.util.Map;
import java.util.Set;

import org.apache.wicket.Component;
import org.apache.wicket.MarkupContainer;

import brix.jcr.wrapper.BrixNode;
import brix.plugin.site.SitePlugin;

/**
 * Helper class for components with custom node markup. This class takes care of
 * generating the markup and creating/removing of appropriate wicket components.
 * 
 * @author Matej Knopp
 */
public class MarkupHelper implements Serializable
{
	public MarkupHelper(MarkupContainer<BrixNode> component)
	{
		this.component = component;
		initMarkup();
	}

	private final MarkupContainer<BrixNode> component;

	/**
	 * Each tag component idis prefixed by this.
	 */
	private final static String COMPONENT_PREFIX = "brix-";

	private String getComponentID(ComponentTag tag)
	{
		String uid = tag.getUniqueId();
		return COMPONENT_PREFIX + (uid != null ? uid.toString() : "");
	}

	private String markup = null;

	public String getMarkup()
	{
		return markup;
	}

	private MarkupCache getMarkupCache()
	{
		return SitePlugin.get().getMarkupCache();
	}
	
	/**
	 * Returns existing tag components on page.
	 * @return
	 */
	private Set<String> getExistingComponents()
	{
		Set<String> result = new HashSet<String>();
		Iterator<Component<?>> i = component.iterator();
		while (i.hasNext())
		{
			Component<?> c = i.next();
			if (c.getId().startsWith(COMPONENT_PREFIX))
			{
				result.add(c.getId());
			}
		}
		return result;
	}

	/**
	 * Generates the markup and makes sure that the markup container contains
	 * all components generated by the {@link ComponentTag}s in markup.
	 * Also removes components no longer present in markup.
	 */
	private void initMarkup()
	{
		final Set<String> existingComponents = getExistingComponents();
		final Set<String> components = new HashSet<String>();
		GeneratedMarkup markup = getMarkupCache().getMarkup(component);
		
		MarkupRenderer renderer = new MarkupRenderer(markup.items, markup.doctype)
		{
			@Override
			void postprocessTagAttributes(Tag tag, Map<String, String> attributes)
			{
				// if during rendering we have a ComponentTag
				if (tag instanceof ComponentTag && tag.getType() != Tag.Type.CLOSE)
				{
					ComponentTag componentTag = (ComponentTag) tag;
					String id = getComponentID(componentTag);
					
					// check if the component already is in hierarchy
					if (existingComponents.contains(id))
					{
						// just put the wicket:id attribute to component tag
						attributes.put("wicket:id", id);
						components.add(id);
					}
					else
					{
						// otherwise we need to create the component instance
						Component<?> c = componentTag.getComponent(id, component.getModel());
						if (c != null)
						{
							attributes.put("wicket:id", id);
							components.add(id);
							component.add(c);
						}
					}
				}
			}
		};
		this.markup = renderer.render();

		// go through existing components and remove those not present in
		// current markup
		for (String s : existingComponents)
		{
			if (!components.contains(s))
			{
				component.get(s).remove();
			}
		}
	}

}
